<<<<<<< HEAD
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
=======
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
>>>>>>> b3183773088a3eded7557d438da9d92c81eac9ba
      - '80:80'